apiVersion: example.com/v1
kind: HPAScaler
metadata:
  name: my-hpa-scaler
spec:
  namespace: test
  hpaName: nginx-hpa
  scheduleStart:
    cronExpression: "* * * * *"
    minReplicas: 2
    maxReplicas: 3
  scheduleEnd:
    cronExpression: "0 0 * * 6-7"
    minReplicas: 1
    maxReplicas: 2
