apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpascalers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                hpaName:
                  type: string
                scheduleStart:
                  type: object
                  properties:
                    cronExpression:
                      type: string
                    minReplicas:
                      type: integer
                      minimum: 1
                    maxReplicas:
                      type: integer
                scheduleEnd:
                  type: object
                  properties:
                    cronExpression:
                      type: string
                    minReplicas:
                      type: integer
                      minimum: 1
                    maxReplicas:
                      type: integer
              required:
                - namespace
                - hpaName
                - scheduleStart
                - scheduleEnd
  scope: Namespaced
  names:
    plural: hpascalers
    singular: hpascaler
    kind: HPAScaler
    shortNames:
      - hps
