apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa-scaler-sa
  namespace: test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hpa-scaler-operator-role
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups:
    - example.com
    resources:
    - hpascalers
    verbs:
    - get
    - list
    - watch 
    - create
    - delete
    - patch
    - update
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa-scaler-operator-binding
subjects:
  - kind: ServiceAccount
    name: hpa-scaler-sa # Replace with your service account name
    namespace: test   # Replace with your desired namespace
roleRef:
  kind: ClusterRole
  name: hpa-scaler-operator-role
  apiGroup: rbac.authorization.k8s.io
